env:
  global:
    secure: IQwgpF5eyNlMnRyaFNSfuOweSshamTwh83J5k6INeZl96agASDufv8OXGGKW2zdgB/AOImahkKAR8EskRE0T1yC0c1+D6msfvlytzq+kzEFbL94F1T9LsnJTnwkrI1p5jGBvoXHZQMPX3cr++SGGkKRoZ2JwywDTT067SuXXufYFUV6p2hDy4Ua68u8yJXVAhsJbzPLhJIopbvcmW348jsZn9aMvl7mvG/jbms9A0pIBUk3DGn9Z8u31csoAbgz5bz07M64mCXwPtETz5aZ6e1NxMYUe6WuvfiIwYhWvw1nvdKN8svL58V6YDfOhsT14hiFi406KcUC2BZqz/PW6k+RpiccYHaTSrzlSG8yWqoshui53rSHJUiN5pZUJYDB55IeuMaYLfHFzkZkA6BJHe9BNb+R6c9DodAHQC4rKujeswhW8OltdLnuuuxerShOMwIv0MODEgurl+7mo5ChLeqAfbrePb8P2yC9Cw7pejVaSDPWH7HhoCceSzFvH18DCbSbSVJchszNXTSLNkvZ883zPOIBZw4+s2lkHWX0NTwq0VZN0V6mtvgKt7SQczJltmwmsZ+LF+/rOZvlIyGoYSoJFT3Al0m7UlNgBBQpTOXyA6NTfc7AN1gEDJEgLYWM8IIAlrQHCtAbUgirJuvwv7rKGY9DPaKV6jKzhos3vVC0=


sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

script:
  - cd doxygen
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doxygen/documentation/html
  on:
    branch: master
