sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - cd doxygen
  - . make_images.sh
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doxygen/documentation/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
